# Configuración de Base de Datos (Aiven)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.application.name=restaurante-backend
server.port=8080

# Configuración JWT (1 día de expiración)
jwt.expiration=86400000

# === NIVELES DE LOG PARA DEPURACIÓN CRÍTICA ===
# Esto te mostrará el paso a paso del filtro de seguridad
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.web.filter.CorsFilter=DEBUG

# Esto te mostrará si hay un error al mapear el JSON de React (Jackson)
logging.level.org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod=TRACE

# Esto te mostrará la consulta SQL exacta que se envía a Aiven
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACEUG